// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bklwfkqwgovsiysrpire.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrbHdma3F3Z292c2l5c3JwaXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTgxMzUsImV4cCI6MjA2NjUzNDEzNX0.0YkUcjMJZsmaXiEvEyoquhaUKNVBEZKpuNNCkLIvm1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);